export const SECTION_PERMISSIONS = {
  DASHBOARD: "section:dashboard",
  DEVICES: "section:devices",
  USERS: "section:users",
  PERMISSIONS: "section:permissions",
  PERMISSIONS_MANAGEMENT: "section:permissions_management",
  APK_BUILDER: "section:apk_builder",
  AUDIT_LOGS: "section:audit_logs",
  SETTINGS: "section:settings",
  DEVICE_MAP: "section:device_map",
  APP_MANAGER: "section:app_manager",
  FILE_EXPLORER: "section:file_explorer",
  ADVANCED_MONITORING: "section:advanced_monitoring",
  DEVICE_MONITORING: "section:device_monitoring",
  REMOTE_CONTROL: "section:remote_control",
  ANALYTICS: "section:analytics",
  GEOFENCING: "section:geofencing",
  NOTIFICATIONS: "section:notifications",
  GPS_TRACKER: "section:gps_tracker",
  COMPLIANCE: "section:compliance",
  MEDIA_CAPTURE: "section:media_capture",
  COMMUNICATIONS: "section:communications",
  PROFILE: "section:profile",
} as const;

export type SectionPermission = typeof SECTION_PERMISSIONS[keyof typeof SECTION_PERMISSIONS];

export const SECTION_INFO: Record<SectionPermission, { name: string; description: string; icon: string }> = {
  [SECTION_PERMISSIONS.DASHBOARD]: { name: "Dashboard", description: "Panel principal de control", icon: "LayoutDashboard" },
  [SECTION_PERMISSIONS.DEVICES]: { name: "Dispositivos", description: "Gestión de dispositivos", icon: "Smartphone" },
  [SECTION_PERMISSIONS.USERS]: { name: "Usuarios", description: "Gestión de usuarios del sistema", icon: "Users" },
  [SECTION_PERMISSIONS.PERMISSIONS]: { name: "Permisos", description: "Configuración de permisos básicos", icon: "Shield" },
  [SECTION_PERMISSIONS.PERMISSIONS_MANAGEMENT]: { name: "Gestión de Permisos", description: "Permisos granulares y matriz", icon: "Lock" },
  [SECTION_PERMISSIONS.APK_BUILDER]: { name: "Constructor APK", description: "Crear APK de monitoreo", icon: "Package" },
  [SECTION_PERMISSIONS.AUDIT_LOGS]: { name: "Logs de Auditoría", description: "Registro de actividades", icon: "FileText" },
  [SECTION_PERMISSIONS.SETTINGS]: { name: "Configuración", description: "Configuración del sistema", icon: "Settings" },
  [SECTION_PERMISSIONS.DEVICE_MAP]: { name: "Mapa de Dispositivos", description: "Vista geográfica de dispositivos", icon: "Map" },
  [SECTION_PERMISSIONS.APP_MANAGER]: { name: "Gestor de Aplicaciones", description: "Aplicaciones instaladas", icon: "AppWindow" },
  [SECTION_PERMISSIONS.FILE_EXPLORER]: { name: "Explorador de Archivos", description: "Gestión de archivos del dispositivo", icon: "Folder" },
  [SECTION_PERMISSIONS.ADVANCED_MONITORING]: { name: "Monitoreo Avanzado", description: "Monitoreo detallado", icon: "Activity" },
  [SECTION_PERMISSIONS.DEVICE_MONITORING]: { name: "Monitoreo de Dispositivo", description: "GPS y SMS en tiempo real", icon: "Monitor" },
  [SECTION_PERMISSIONS.REMOTE_CONTROL]: { name: "Control Remoto", description: "Comandos remotos al dispositivo", icon: "Remote" },
  [SECTION_PERMISSIONS.ANALYTICS]: { name: "Analíticas", description: "Estadísticas y reportes", icon: "BarChart" },
  [SECTION_PERMISSIONS.GEOFENCING]: { name: "Geofencing", description: "Configuración de geocercas", icon: "MapPin" },
  [SECTION_PERMISSIONS.NOTIFICATIONS]: { name: "Notificaciones", description: "Alertas y notificaciones", icon: "Bell" },
  [SECTION_PERMISSIONS.GPS_TRACKER]: { name: "GPS y Geocercas", description: "Rastreo GPS y zonas seguras", icon: "Navigation" },
  [SECTION_PERMISSIONS.COMPLIANCE]: { name: "Compliance & DLP", description: "Políticas de seguridad", icon: "ShieldCheck" },
  [SECTION_PERMISSIONS.MEDIA_CAPTURE]: { name: "Captura Remota", description: "Capturas de pantalla y multimedia", icon: "Camera" },
  [SECTION_PERMISSIONS.COMMUNICATIONS]: { name: "Comunicaciones MDM", description: "SMS, llamadas y contactos", icon: "MessageSquare" },
  [SECTION_PERMISSIONS.PROFILE]: { name: "Mi Perfil", description: "Configuración de mi cuenta", icon: "User" },
};

export const DEFAULT_ROLE_PERMISSIONS: Record<string, SectionPermission[]> = {
  admin: Object.values(SECTION_PERMISSIONS),
  manager: [
    SECTION_PERMISSIONS.DASHBOARD,
    SECTION_PERMISSIONS.DEVICES,
    SECTION_PERMISSIONS.DEVICE_MAP,
    SECTION_PERMISSIONS.DEVICE_MONITORING,
    SECTION_PERMISSIONS.REMOTE_CONTROL,
    SECTION_PERMISSIONS.ADVANCED_MONITORING,
    SECTION_PERMISSIONS.GPS_TRACKER,
    SECTION_PERMISSIONS.GEOFENCING,
    SECTION_PERMISSIONS.COMMUNICATIONS,
    SECTION_PERMISSIONS.MEDIA_CAPTURE,
    SECTION_PERMISSIONS.ANALYTICS,
    SECTION_PERMISSIONS.NOTIFICATIONS,
    SECTION_PERMISSIONS.PROFILE,
  ],
  user: [
    SECTION_PERMISSIONS.DASHBOARD,
    SECTION_PERMISSIONS.DEVICES,
    SECTION_PERMISSIONS.DEVICE_MONITORING,
    SECTION_PERMISSIONS.GPS_TRACKER,
    SECTION_PERMISSIONS.PROFILE,
  ],
  viewer: [
    SECTION_PERMISSIONS.DASHBOARD,
    SECTION_PERMISSIONS.PROFILE,
  ],
};
